### ISSUE TITLE
How to connect cables for firmware update?

### ISSUE THREAD

**Issue by jurohosoi** [shinolab/autd3#2]
I would like to perform a firmware update, but I am unsure how to connect the 'XILINX Platform Cable, the J-Link Plus & J-Link 9-Pin Cortex-M Adapter' to the AUTD. Could you provide any information (e.g., images) on how to connect each device and which connectors on the AUTD should be used respectively?

**Comment by s5suzuki** [comment]
Thanks for your suggestion.
I have added a photo to the document.
https://shinolab.github.io/autd3-doc/jp/Users_Manual/getting_started.html

**Comment by jurohosoi** [comment]
Thank you for providing the valuable information. I successfully completed the firmware update following your instructions.
